# vim:ft=kitty
## name: Wallpaper — hadrut_dark.jpeg
foreground #d2cbbc
background #291c25
selection_foreground #d2cbbc
selection_background #3c2836
cursor #d2cbbc
cursor_text_color #291c25
url_color #c29fc6
active_border_color #d9d4a1
inactive_border_color #705c6a
bell_border_color #cb8a86
active_tab_foreground #291c25
active_tab_background #d9d4a1
inactive_tab_foreground #d2cbbc
inactive_tab_background #3c2836
tab_bar_background #291c25
mark1_foreground #291c25
mark1_background #d9d4a1
mark2_foreground #291c25
mark2_background #cb8a86
mark3_foreground #291c25
mark3_background #c29fc6
color0 #3c2836
color1 #cb8a86
color2 #86cb86
color3 #cbc586
color4 #8696cb
color5 #cb86ab
color6 #869acb
color7 #c2bcad
color8 #6b5765
color9 #d9a5a1
color10 #a1d9a1
color11 #d9d4a1
color12 #a1aed9
color13 #d9a1bf
color14 #a1b1d9
color15 #e2ded5
