# vim:ft=kitty
## name: Srcery

# Basic colors
foreground           #FCE8C3
background           #121110
selection_foreground #FCE8C3
selection_background #3B3935

# Cursor colors
cursor            #FCE8C3
cursor_text_color #0E0D0C

# URL underline color when hovering with mouse
url_color #68A8E4

# Window border colors and terminal bell colors
active_border_color   #FF5F00
inactive_border_color #504D47
bell_border_color     #EF2F27
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #0E0D0C
active_tab_background   #FF5F00
inactive_tab_foreground #FCE8C3
inactive_tab_background #262522
tab_bar_background      #121110
tab_bar_margin_color    none

# Mark colors
mark1_foreground #0E0D0C
mark1_background #FF5F00
mark2_foreground #0E0D0C
mark2_background #EF2F27
mark3_foreground #0E0D0C
mark3_background #68A8E4

# Srcery ANSI palette
color0  #121110
color1  #EF2F27
color2  #519F50
color3  #FBB829
color4  #2C78BF
color5  #E02C6D
color6  #0AAEB3
color7  #C5B088
color8  #917E6B
color9  #F75341
color10 #98BC37
color11 #FED06E
color12 #68A8E4
color13 #FF5C8F
color14 #2BE4D0
color15 #FCE8C3
