#!/bin/sh
# Regenerates src/keysym_data.odin from the system X11 keysym header.
#   usage: scripts/gen_keysyms.sh [header] > src/keysym_data.odin
# Only needs a POSIX awk; run when the installed keysym list must change.
HDR="${1:-/usr/include/X11/keysymdef.h}"
{
  echo "package main"
  echo ""
  echo "// GENERATED by scripts/gen_keysyms.sh - do not edit by hand."
  echo "// One row per #define XK_<name> <value> from the X11 keysym header."
  echo "// Keysym names are ASCII identifiers, so no quoting is required."
  echo "XK_Entry :: struct { name: string, value: u32 }"
  echo "keysym_names := [?]XK_Entry{"
  awk '
    /^#define[ \t]+XK_[A-Za-z0-9_]+[ \t]+0x[0-9A-Fa-f]+/ {
      name = $2; sub(/^XK_/, "", name)
      printf "    {\"%s\", %s},\n", name, $3
    }' "$HDR"
  echo "}"
} 
